// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.1
// source: actor/actor.proto

package actor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *PID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *PID                   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetFrom() *PID {
	if x != nil {
		return x.From
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *PID                   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_actor_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_actor_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_actor_actor_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetFrom() *PID {
	if x != nil {
		return x.From
	}
	return nil
}

var File_actor_actor_proto protoreflect.FileDescriptor

const file_actor_actor_proto_rawDesc = "" +
	"\n" +
	"\x11actor/actor.proto\x12\x05actor\"/\n" +
	"\x03PID\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\"&\n" +
	"\x04Ping\x12\x1e\n" +
	"\x04from\x18\x01 \x01(\v2\n" +
	".actor.PIDR\x04from\"&\n" +
	"\x04Pong\x12\x1e\n" +
	"\x04from\x18\x01 \x01(\v2\n" +
	".actor.PIDR\x04fromB&Z$github.com/khulnasoft/goactors/actorb\x06proto3"

var (
	file_actor_actor_proto_rawDescOnce sync.Once
	file_actor_actor_proto_rawDescData []byte
)

func file_actor_actor_proto_rawDescGZIP() []byte {
	file_actor_actor_proto_rawDescOnce.Do(func() {
		file_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_actor_proto_rawDesc), len(file_actor_actor_proto_rawDesc)))
	})
	return file_actor_actor_proto_rawDescData
}

var file_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_actor_actor_proto_goTypes = []any{
	(*PID)(nil),  // 0: actor.PID
	(*Ping)(nil), // 1: actor.Ping
	(*Pong)(nil), // 2: actor.Pong
}
var file_actor_actor_proto_depIdxs = []int32{
	0, // 0: actor.Ping.from:type_name -> actor.PID
	0, // 1: actor.Pong.from:type_name -> actor.PID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_actor_actor_proto_init() }
func file_actor_actor_proto_init() {
	if File_actor_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_actor_proto_rawDesc), len(file_actor_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_actor_proto_goTypes,
		DependencyIndexes: file_actor_actor_proto_depIdxs,
		MessageInfos:      file_actor_actor_proto_msgTypes,
	}.Build()
	File_actor_actor_proto = out.File
	file_actor_actor_proto_goTypes = nil
	file_actor_actor_proto_depIdxs = nil
}
